### PR TITLE
Fix file name decoding in getFileInfoByName

### LINKED ISSUE #37: getFileInfoByName does not decode file name
`getFileInfo` returns the correct file name for a file, but `getFileInfoByName` is not decoding the url-encoded file name returned in the headers.

My test that exercises non-ASCII unicode characters reports this about the file name returned by `getFileInfoByName`:

```
file name: ERROR
    expected: !#%')+-/13/579;=?ACEGIKMOQSUWY[/]_acegikmoqsuwy{}²/äĖňźƬǞȐɂɴʦ˘̼̊ͮΠϒЄжѨҚ/ӌӾ԰բ֔׆׸تٜڎۀ۲ܤݖވ޺߬ࠞ࠲ࡆ/࡚࡮ࢂ࢖ࢪࢾ࣒ࣦࣺऎढशॊफ़ॲআচমূ৖/৪৾਒ਦ਺੎੢੶ઊઞલ૆૚૮ଂଖପା୒୦/୺எ஢ஶொ௞௲ఆచమూౖ౪౾ಒದ಺೎ೢ೶/ഊഞലെ൚൮ංඖඪ඾ි෦෺ฎยึ๊๞๲ຆ/ບຮໂ໖໪AA
    actual:   !%23%25')%2B-/13/579;=%3FACEGIKMOQSUWY%5B/%5D_acegikmoqsuwy%7B%7D%C2%80%C2%B2/%C3%A4%C4%96%C5%88%C5%BA%C6%AC%C7%9E%C8%90%C9%82%C9%B4%CA%A6%CB%98%CC%8A%CC%BC%CD%AE%CE%A0%CF%92%D0%84%D0%B6%D1%A8%D2%9A/%D3%8C%D3%BE%D4%B0%D5%A2%D6%94%D7%86%D7%B8%D8%AA%D9%9C%DA%8E%DB%80%DB%B2%DC%A4%DD%96%DE%88%DE%BA%DF%AC%E0%A0%9E%E0%A0%B2%E0%A1%86/%E0%A1%9A%E0%A1%AE%E0%A2%82%E0%A2%96%E0%A2%AA%E0%A2%BE%E0%A3%92%E0%A3%A6%E0%A3%BA%E0%A4%8E%E0%A4%A2%E0%A4%B6%E0%A5%8A%E0%A5%9E%E0%A5%B2%E0%A6%86%E0%A6%9A%E0%A6%AE%E0%A7%82%E0%A7%96/%E0%A7%AA%E0%A7%BE%E0%A8%92%E0%A8%A6%E0%A8%BA%E0%A9%8E%E0%A9%A2%E0%A9%B6%E0%AA%8A%E0%AA%9E%E0%AA%B2%E0%AB%86%E0%AB%9A%E0%AB%AE%E0%AC%82%E0%AC%96%E0%AC%AA%E0%AC%BE%E0%AD%92%E0%AD%A6/%E0%AD%BA%E0%AE%8E%E0%AE%A2%E0%AE%B6%E0%AF%8A%E0%AF%9E%E0%AF%B2%E0%B0%86%E0%B0%9A%E0%B0%AE%E0%B1%82%E0%B1%96%E0%B1%AA%E0%B1%BE%E0%B2%92%E0%B2%A6%E0%B2%BA%E0%B3%8E%E0%B3%A2%E0%B3%B6/%E0%B4%8A%E0%B4%9E%E0%B4%B2%E0%B5%86%E0%B5%9A%E0%B5%AE%E0%B6%82%E0%B6%96%E0%B6%AA%E0%B6%BE%E0%B7%92%E0%B7%A6%E0%B7%BA%E0%B8%8E%E0%B8%A2%E0%B8%B6%E0%B9%8A%E0%B9%9E%E0%B9%B2%E0%BA%86/%E0%BA%9A%E0%BA%AE%E0%BB%82%E0%BB%96%E0%BB%AAAA
```

### PR DESCRIPTION
**Pull request by bwbeach**
fixes #37

### CODE REVIEW

**Comment by certainmagic** [comment]
thanks for finding the problem and making a fix for it, BrianB!  :)

File: core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java [hunk 1]
```diff
@@ -466,9 +468,16 @@ public B2FileVersion getFileInfoByName(B2AccountAuthorization accountAuth,
                 request.getFileName()), makeHeaders(accountAuth));
 
 
-        return new B2FileVersion(headers.getValueOrNull(FILE_ID), headers.getValueOrNull(FILE_NAME),
-                headers.getContentLength(), headers.getContentType(), headers.getContentSha1OrNull(),
-                headers.getB2FileInfo(), "upload", Long.parseLong(headers.getValueOrNull(UPLOAD_TIMESTAMP)));
+        return new B2FileVersion(
+                headers.getValueOrNull(FILE_ID),
+                percentDecode(headers.getValueOrNull(FILE_NAME)),
```
Comment (certainmagic) [inline core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java]: what would you think about adding a B2Headers.getFileName() that would do this decode.  it could help prevent other people from forgetting to do the decode.

Comment (certainmagic) [reply core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java]: i discussed this with BrianB offline and I'll be making that change.

File: core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java [hunk 2]
```diff
@@ -85,6 +92,42 @@ default long getContentLength() {
...
+
+    /**
+     * @return the value of the X-Bz-Upload-Timestamp header (parsed as a long)
+     *         or null if that header isn't present or can't be parsed.
+     * @apiNote We return null here because this is a completely optional, non-standard header
+     *          and anyone could put any type of value in it at any time.
+     */
+    default Long getUploadTimestampOrNull() {
+        final String str = getValueOrNull(B2Headers.UPLOAD_TIMESTAMP);
+        B2Preconditions.checkState(str != null, "don't call if there isn't a b2 filename");
```
Comment (bwbeach) [inline core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java]: wrong error message.

Comment (certainmagic) [reply core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java]: thanks.  it's even worse than that.  the comment says we'll return null if it's not present and the code is throwing an exception.  i've added tests and updated the code.
